services:
  # MongoDB database
  mongodb:
    image: mongo:7
    container_name: ielts-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ielts-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ielts-backend
    restart: unless-stopped
    ports:
      - "8080:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/ielts-mock?authSource=admin
    depends_on:
      - mongodb
    networks:
      - ielts-network

  # Frontend web app
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ielts-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ielts-network

volumes:
  mongodb_data:
    driver: local

networks:
  ielts-network:
    driver: bridge